### Based from https://github.com/luckyframework/lucky/blob/master/.github/workflows/ci.yml

name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        shard_file:
          - shard.yml
        crystal_version:
          - 0.36.1
          - 1.0.0
        experimental:
          - false
        include:
          - shard_file: shard.yml
            crystal_version: nightly
            experimental: true

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal_version }}-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Cache Crystal
        uses: actions/cache@v1
        with:
          path: ~/.cache/crystal
          key: ${{ runner.os }}-crystal

      - name: Install shards
        run: SHARDS_OVERRIDE=${{ matrix.shard_file }} shards install --ignore-crystal-version

      - name: Run tests
        run: crystal spec
