### Based from https://github.com/luckyframework/lucky/blob/master/.github/workflows/ci.yml

name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - "*"

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        shard_file:
          - shard.yml
        crystal_version:
          - 0.36.1
          - 1.0.0
          - 1.1.0
          - 1.2.0
          - 1.3.0
          - 1.4.0
          - 1.5.0
        include:
          - shard_file: shard.yml
            crystal_version: latest
            ignore_errors: true

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ignore_errors || false }}
    container: crystallang/crystal:${{ matrix.crystal_version }}

    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}

      - name: Run tests
        run: crystal spec
